// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCePAv3QSdt_stYD4Z7dIeMPG0i2ITXxgU',
    appId: '1:922618668136:web:d8066cfaa08a664bed87dd',
    messagingSenderId: '922618668136',
    projectId: 'chat-app-1-ce751',
    authDomain: 'chat-app-1-ce751.firebaseapp.com',
    storageBucket: 'chat-app-1-ce751.firebasestorage.app',
    measurementId: 'G-G54NZP3LX1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWwRDTaF6-v2-f0Yik9S0Msw5OU3-7a9w',
    appId: '1:922618668136:android:3aacebd81eab055bed87dd',
    messagingSenderId: '922618668136',
    projectId: 'chat-app-1-ce751',
    storageBucket: 'chat-app-1-ce751.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBc3spWpzflZN_pdQYlRDe-v8wY5HZgnz4',
    appId: '1:922618668136:ios:6654e6775e764220ed87dd',
    messagingSenderId: '922618668136',
    projectId: 'chat-app-1-ce751',
    storageBucket: 'chat-app-1-ce751.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBc3spWpzflZN_pdQYlRDe-v8wY5HZgnz4',
    appId: '1:922618668136:ios:6654e6775e764220ed87dd',
    messagingSenderId: '922618668136',
    projectId: 'chat-app-1-ce751',
    storageBucket: 'chat-app-1-ce751.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCePAv3QSdt_stYD4Z7dIeMPG0i2ITXxgU',
    appId: '1:922618668136:web:633b4d40079af71aed87dd',
    messagingSenderId: '922618668136',
    projectId: 'chat-app-1-ce751',
    authDomain: 'chat-app-1-ce751.firebaseapp.com',
    storageBucket: 'chat-app-1-ce751.firebasestorage.app',
    measurementId: 'G-1G0WNX9G1Z',
  );
}
